### ISSUE TITLE
Example on how to send OOK codes

### ISSUE THREAD

**Issue by probonopd** [mrmx/Arduino-SI4012#2]
Hello, I am tryigng to find out whether Arduino-SI4012 could be used to [control a 27.145 MHz BOSE Lifestyle](https://github.com/probonopd/Lifestyle/issues/8) system.

Would it be possible to send the following signal (the numbers are in microseconds, with "+" meaning "27.145 MHz on", and "-" meaning "27.145 MHz off"?

+9024 -4512 +564 -564 +564 -1692 +564 -564 +564 -1692 +564 -1692 +564 -1692 +564 -564 +564 -1692 +564 -1692 +564 -564 +564 -1692 +564 -564 +564 -1692 +564 -564 +564 -1692 +564 -564 +564 -1692 +564 -564 +564 -564 +564 -564 +564 -564 +564 -564 +564 -564 +564 -564 +564 -564 +564 -1692 +564 -1692 +564 -1692 +564 -1692 +564 -1692 +564 -1692 +564 -1692 +564 -38628

How would the code look for this?

**Comment by mrmx** [comment]
If you hack a routine to make such pulses to fill the fifo buffer for a matching baudrate (for OOK the smallest pulse is of 1/50000 sec) it could be done. :-)

**Comment by sandmix** [comment]
Sure this are not microseconds ?

**Comment by sandmix** [comment]
would it be possible to emulate something like this:
{
    "name": "jsbr RC Car",
    "description": "Ford Mustang, 40MHz, No. 23819",
    "frequency": 40.0,
    "synchronization_burst_us": 1200,
    "synchronization_spacing_us": 500,
    "total_synchronizations": 4,
    "signal_burst_us": 400,
    "signal_spacing_us": 400,

    "forward": 11,
	"left": 59,
    "forward_left": 27,
	"right": 64,
    "forward_right": 33,
    "reverse": 39,
    "reverse_left": 51,
    "reverse_right": 45
}

**Comment by probonopd** [comment]
Microseconds, you are right :)
