### ISSUE TITLE
Si4012.cpp

### ISSUE THREAD

**Issue by brandon234801** [mrmx/Arduino-SI4012#4]
In Si4012.cpp, is line 56 supposed to be 
reqBuf[3] = rampRate & 0xF;
or is it supposed to be
reqBuf[3] = rampRate & 0xF**F**; 

I was also wondering if there is a more detailed "how to" manual for those not totally familiar with coding. 

Thanks!

**Comment by mrmx** [comment]
As per datasheet page 36 yes the rampRate 3rd data is clamped to 4bits.
